# Generated by Django 5.1.1 on 2024-09-13 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_post_tags_alter_tag_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='slug',
            field=models.SlugField(default='temp_slug', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
